baseURL = "http://example.org/"
languageCode = "en-us"
title = "Deep Ford FATE"
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
publishDir = "docs"

