baseURL = "https://hamptonsmith.github.io/deep-ford/"
languageCode = "en-us"
title = "Deep Ford FATE"
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
publishDir = "docs"
